### ISSUE TITLE
Leaves behind multiple solargraph processes

### ISSUE THREAD

**Issue by yoru** [uplus/deoplete-solargraph#2]
First, thank you for this great plugin.
I just noticed a sudden increase in ram usage, it looks like the processes are not killed and are still running in the background

![screenshot](https://my.mixtape.moe/gxupcq.png)

**Comment by uplus** [comment]
I also have the same problem. But, it occur randomly.
I don't hava time to find the cause :cry:

**Comment by halftan** [comment]
hopefully PR #3  will resolve this issue

**Comment by uplus** [comment]
@yoru
This problem probably solved by the following PR.
https://github.com/uplus/solargraph-utils.py/pull/2
Please try it.

You need to execute the following command to apply this fix
`pip install --upgrade solargraph-utils.py`

**Comment by uplus** [comment]
Probably, it was solved.
If the problem is not solved, please reopen it.
